# Generated by Django 4.1.7 on 2023-05-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_comment_name_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionForItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('date_foundation', models.CharField(blank=True, max_length=30)),
                ('parking', models.BooleanField(blank=True)),
                ('average_check', models.FloatField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
